version: "3"

tasks:
  test:
    cmds:
      - docker compose run --build --rm -e NODE_ENV=test k8sproxy bun test
  dev:
    cmds:
      - docker compose run --build --rm k8sproxy
  prod:
    cmds:
      - docker compose -f compose.yml -f compose.prod.yml up --build
